[package]
name = "console-front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
engine = { path = '../engine' }
tokio = { version = "1.21", features = ['full'] }
